application: appintheairserver
version: 1
runtime: php55
api_version: 1
#threadsafe: yes TODO

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: main.php


#- url: /
#  script: home.php
#
#- url: /index\.html
#  script: home.php
#
#- url: /stylesheets
#  static_dir: stylesheets
#
#- url: /(.*\.(gif|png|jpg))$
#  static_files: static/\1
#  upload: static/.*\.(gif|png|jpg)$
#
#- url: /admin/.*
#  script: admin.php
#  login: admin
#
#- url: /.*
#  script: not_found.php